name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: npm i
    - name: publish
      run: npm run publish:token ${{ secrets.VSCE_TOKEN }}
